$ErrorActionPreference = 'Stop'
$repoDir = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$failures = 0
function Pass($m){ Write-Host "PASS $m" }
function Fail($m){ Write-Host "FAIL $m" -ForegroundColor Red; $script:failures++ }
function Normalize-RepoPath($p){ $d = Split-Path -Parent $p; if ((Resolve-Path $d).Path -eq $repoDir) { Split-Path -Leaf $p } else { ((Resolve-Path $d).Path.Substring($repoDir.Length + 1)) + '/' + (Split-Path -Leaf $p) } }
function Resolve-RelativeLink($sourceFile,$linkPath){ $sourceDir = Split-Path -Parent $sourceFile; $candidate = Join-Path $sourceDir $linkPath; if (Test-Path $candidate -PathType Leaf) { return (Resolve-Path $candidate).Path }; if (Test-Path $candidate -PathType Container -and (Test-Path (Join-Path $candidate 'index.md') -PathType Leaf)) { return (Resolve-Path (Join-Path $candidate 'index.md')).Path }; if ($linkPath.EndsWith('/')) { if (Test-Path (Join-Path $candidate 'index.md') -PathType Leaf) { return (Resolve-Path (Join-Path $candidate 'index.md')).Path } } elseif (Test-Path "$candidate.md" -PathType Leaf) { return (Resolve-Path "$candidate.md").Path } elseif (Test-Path (Join-Path $candidate 'index.md') -PathType Leaf) { return (Resolve-Path (Join-Path $candidate 'index.md')).Path }; return $null }
function Resolve-RootDocsLink($linkPath){ $docsTarget = $linkPath.TrimStart('/'); $candidate = Join-Path $repoDir ("docs/$docsTarget"); if (-not $docsTarget) { $idx = Join-Path $repoDir 'docs/index.md'; if (Test-Path $idx -PathType Leaf) { return (Resolve-Path $idx).Path }; return $null } if (Test-Path $candidate -PathType Leaf) { return (Resolve-Path $candidate).Path } if (Test-Path $candidate -PathType Container -and (Test-Path (Join-Path $candidate 'index.md') -PathType Leaf)) { return (Resolve-Path (Join-Path $candidate 'index.md')).Path } if ($docsTarget.EndsWith('/')) { if (Test-Path (Join-Path $candidate 'index.md') -PathType Leaf) { return (Resolve-Path (Join-Path $candidate 'index.md')).Path } } elseif (Test-Path "$candidate.md" -PathType Leaf) { return (Resolve-Path "$candidate.md").Path } elseif (Test-Path (Join-Path $candidate 'index.md') -PathType Leaf) { return (Resolve-Path (Join-Path $candidate 'index.md')).Path }; return $null }
$files = @((Join-Path $repoDir 'README.md'), (Join-Path $repoDir 'README.zh-CN.md')) + (Get-ChildItem -LiteralPath (Join-Path $repoDir 'docs') -Recurse -File -Filter '*.md').FullName
foreach ($file in $files) { Pass "scan_file:$((Resolve-Path $file).Path.Substring($repoDir.Length + 1))"; foreach ($m in [regex]::Matches((Get-Content -Raw -LiteralPath $file), '!?\[[^\[\]]*\]\(([^)]+)\)')) { $target = $m.Groups[1].Value.Trim(); if ($target -match '^(#|http://|https://|mailto:)' -or $target -match '^[A-Za-z][A-Za-z0-9+.-]*:') { continue }; $path = ($target -split '#|\?')[0]; if (-not $path) { continue }; $resolved = if ($path.StartsWith('/')) { Resolve-RootDocsLink $path } else { Resolve-RelativeLink $file $path }; if ($resolved) { Pass "doc_link:$((Resolve-Path $file).Path.Substring($repoDir.Length + 1)):$($m.Index):$target -> $(Normalize-RepoPath $resolved)" } else { Fail "doc_link:$((Resolve-Path $file).Path.Substring($repoDir.Length + 1)):$($m.Index):$target" } } }
if ($failures -gt 0) { exit 1 }
Pass 'doc_link_integrity'
